"""Render a Report as a self-contained HTML page."""

from __future__ import annotations

from jinja2 import Template

from econoclast.report.models import Report

_BAND_COLOR = {
    "Robust": "#1a7f37",
    "Minor concerns": "#9a6700",
    "Material concerns": "#bc4c00",
    "Fragile": "#cf222e",
    "Severe": "#82071e",
}
_SEV_COLOR = {
    "critical": "#82071e", "high": "#cf222e", "medium": "#bc4c00",
    "low": "#0969da", "info": "#6e7781",
}

_HTML = Template(
    """<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Econoclast review — {{ r.paper_title }}</title>
<style>
:root { --fg:#1f2328; --muted:#656d76; --bg:#fff; --line:#d0d7de; }
* { box-sizing:border-box; }
body { font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif;
  color:var(--fg); margin:0; background:#f6f8fa; line-height:1.55; }
.wrap { max-width:900px; margin:0 auto; padding:32px 20px 80px; }
h1 { font-size:1.7rem; margin:0 0 4px; }
.sub { color:var(--muted); margin:0 0 24px; }
.gauge { display:flex; align-items:center; gap:20px; background:var(--bg); border:1px solid var(--line);
  border-radius:12px; padding:22px 24px; margin-bottom:24px; }
.score { font-size:3rem; font-weight:800; line-height:1; }
.band { font-weight:700; font-size:1.15rem; }
.bar { height:10px; border-radius:6px; background:#eaeef2; overflow:hidden; margin-top:8px; }
.bar > div { height:100%; }
.card { background:var(--bg); border:1px solid var(--line); border-radius:10px; padding:18px 20px; margin:14px 0; }
.tag { display:inline-block; font-size:.72rem; font-weight:700; text-transform:uppercase;
  letter-spacing:.03em; color:#fff; padding:2px 8px; border-radius:20px; margin-right:6px; }
.meta-tags { color:var(--muted); font-size:.85rem; margin:6px 0 10px; }
blockquote { border-left:3px solid var(--line); margin:10px 0; padding:4px 14px; color:#414b56;
  background:#f6f8fa; border-radius:0 6px 6px 0; font-size:.92rem; }
table { width:100%; border-collapse:collapse; font-size:.9rem; margin-top:10px; }
th,td { text-align:left; padding:8px 10px; border-bottom:1px solid var(--line); vertical-align:top; }
th { color:var(--muted); font-weight:600; }
.fix { font-size:.9rem; background:#ddf4ff; border-radius:6px; padding:8px 12px; margin-top:8px; }
.footer { color:var(--muted); font-size:.8rem; margin-top:40px; border-top:1px solid var(--line); padding-top:16px; }
h2 { margin-top:34px; border-bottom:1px solid var(--line); padding-bottom:6px; }
.integrity { background:#fff8c5; border:1px solid #d4a72c; border-radius:8px; padding:10px 14px; margin:14px 0; }
</style></head>
<body><div class="wrap">
<h1>Econoclast adversarial review</h1>
<p class="sub">{{ r.paper_title }}<br>
<small>{{ r.designs | join(", ") if r.designs else "design unclear / descriptive" }}
 · {{ r.n_claims }} statistical claims extracted</small></p>

<div class="gauge">
  <div class="score" style="color:{{ band_color }}">{{ frag.score }}</div>
  <div style="flex:1">
    <div class="band" style="color:{{ band_color }}">{{ frag.band }} <span style="color:var(--muted);font-weight:400">/ 100 fragility</span></div>
    <div>{{ frag.band_blurb }}</div>
    <div class="bar"><div style="width:{{ frag.score }}%; background:{{ band_color }}"></div></div>
  </div>
</div>
{% if frag.integrity_violation %}<div class="integrity"><b>Integrity flag:</b> at least one reported statistic is internally impossible or inconsistent.</div>{% endif %}

{% if referee.headline %}<h2>Referee summary</h2>
<div class="card"><b>{{ referee.headline }}</b><p>{{ referee.assessment }}</p>
{% if referee.what_would_change_my_mind %}<p><b>What would change the verdict:</b> {{ referee.what_would_change_my_mind }}</p>{% endif %}</div>{% endif %}

<h2>Findings ({{ findings | length }})</h2>
{% if not findings %}<p>No findings raised.</p>{% endif %}
{% for f in findings %}
<div class="card">
  <div><span class="tag" style="background:{{ sev_color(f.severity) }}">{{ f.severity }}</span>
  <b>{{ f.title }}</b></div>
  <div class="meta-tags">{{ f.category }} · confidence {{ "%.0f"|format(f.confidence*100) }}% · {{ f.attack }}{% if f.locations %} · {{ f.locations | join(", ") }}{% endif %}</div>
  <div>{{ f.detail }}</div>
  {% for q in f.evidence %}<blockquote>{{ q }}</blockquote>{% endfor %}
  {% if f.recommendation %}<div class="fix"><b>Fix:</b> {{ f.recommendation }}</div>{% endif %}
</div>
{% endfor %}

<h2>Deterministic forensic battery</h2>
<table><tr><th>Test</th><th>Verdict</th><th>Inputs</th><th>Summary</th></tr>
{% for t in forensics %}<tr><td><code>{{ t.name }}</code></td><td>{{ t.verdict }}</td><td>{{ t.n_inputs }}</td><td>{{ t.summary }}</td></tr>{% endfor %}
</table>

<div class="footer">
Generated by Econoclast v{{ meta.version }}{% if meta.timestamp %} on {{ meta.timestamp }}{% endif %}.
Models: {{ meta.models | join(", ") if meta.models else "none (deterministic only)" }}.
LLM calls {{ meta.usage.calls if meta.usage else 0 }}, tokens {{ meta.usage.total_tokens if meta.usage else 0 }}, est. cost ${{ "%.4f"|format(meta.usage.est_cost_usd if meta.usage else 0) }}.
<p><b>Disclaimer:</b> Econoclast is a screening tool. Findings are hypotheses for a human to verify, not verdicts of misconduct.</p>
</div>
</div></body></html>
"""
)


def render_html(report: Report) -> str:
    band_color = _BAND_COLOR.get(report.fragility.get("band", ""), "#656d76")
    return _HTML.render(
        r=report,
        frag=report.fragility,
        referee=report.referee or {},
        findings=report.findings_sorted(),
        forensics=report.forensic_results,
        meta=report.meta,
        band_color=band_color,
        sev_color=lambda s: _SEV_COLOR.get(s, "#6e7781"),
    )
