"""Render a Report as Markdown."""

from __future__ import annotations

from jinja2 import Template

from econoclast.report.models import Report

_SEV_EMOJI = {"critical": "🟥", "high": "🟧", "medium": "🟨", "low": "🟦", "info": "⬜"}

_MD = Template(
    """# Econoclast adversarial review

**Paper:** {{ r.paper_title }}
**Design(s):** {{ r.designs | join(", ") if r.designs else "unclear / descriptive" }}
**Statistical claims extracted:** {{ r.n_claims }}

## Fragility: {{ frag.score }}/100 — {{ frag.band }}
> {{ frag.band_blurb }}
{% if frag.integrity_violation %}
> ⚠️ **Integrity flag:** at least one reported statistic is internally impossible or inconsistent.
{% endif %}

| Severity | Count |
|---|---|
{% for sev in ["critical","high","medium","low"] %}{% if frag.by_severity.get(sev) %}| {{ _emoji(sev) }} {{ sev }} | {{ frag.by_severity[sev] }} |
{% endif %}{% endfor %}

{% if referee.headline %}## Referee summary

**{{ referee.headline }}**

{{ referee.assessment }}
{% if referee.what_would_change_my_mind %}
**What would change the verdict:** {{ referee.what_would_change_my_mind }}
{% endif %}
{% endif %}
## Findings ({{ findings | length }})

{% if not findings %}_No findings raised._{% endif %}
{% for f in findings %}
### {{ loop.index }}. {{ _emoji(f.severity) }} {{ f.title }}
`{{ f.severity }}` · `{{ f.category }}` · confidence {{ "%.0f"|format(f.confidence * 100) }}% · _{{ f.attack }}_{% if f.locations %} · {{ f.locations | join(", ") }}{% endif %}

{{ f.detail }}
{% for q in f.evidence %}
> {{ q }}
{% endfor %}{% if f.recommendation %}
**Fix:** {{ f.recommendation }}
{% endif %}
{% endfor %}
## Deterministic forensic battery

| Test | Verdict | Inputs | Summary |
|---|---|---|---|
{% for t in forensics %}| `{{ t.name }}` | {{ _verdict(t.verdict) }} | {{ t.n_inputs }} | {{ t.summary | replace("\n"," ") | truncate(140) }} |
{% endfor %}

---
<sub>Generated by Econoclast v{{ meta.version }}{% if meta.timestamp %} on {{ meta.timestamp }}{% endif %}.
Models: {{ meta.models | join(", ") if meta.models else "none (deterministic only)" }}.
LLM calls: {{ meta.usage.calls if meta.usage else 0 }}, tokens: {{ meta.usage.total_tokens if meta.usage else 0 }}, est. cost: ${{ "%.4f"|format(meta.usage.est_cost_usd if meta.usage else 0) }}.
Attacks run: {{ meta.attacks_run | join(", ") }}{% if meta.attacks_skipped %}; skipped: {{ meta.attacks_skipped | join(", ") }}{% endif %}.

**Disclaimer:** Econoclast is a screening tool. Findings are hypotheses for a human to verify, not verdicts of misconduct. Deterministic inconsistencies can be honest typos; statistical signals (p-curve, caliper, TIVA, Benford) are weak on small samples and assume conditions that a single paper may not meet.</sub>
"""
)


def _verdict_md(v: str) -> str:
    return {
        "suspicious": "⚠️ suspicious",
        "clean": "✅ clean",
        "inconclusive": "➖ inconclusive",
        "insufficient_data": "· n/a",
    }.get(v, v)


def render_markdown(report: Report) -> str:
    return _MD.render(
        r=report,
        frag=report.fragility,
        referee=report.referee or {},
        findings=report.findings_sorted(),
        forensics=report.forensic_results,
        meta=report.meta,
        _emoji=lambda s: _SEV_EMOJI.get(s, "•"),
        _verdict=_verdict_md,
    )
